apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-viewer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
  